#  name [K|SP|SQ|W] EigenID ZielID Wert
- [Spannungsquelle, 4, 0 ,1 ,100]
- [R1,1, 0 , 1, 100]
- [R2,1, 0 , 2, 100]
- [R3,1, 0 , 3, 100]
- [R4,1, 0 , 4, 100]
- [R1,1, 1 , 0, 20]
- [R2,1, 2 , 0, 40]
- [R3,1, 3 , 0, 50]
- [R4,1, 4 , 0, 60]
